// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```darts
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8hv-GBAXiQHlPMpL-ltfvrAJHfoTw5D8',
    appId: '1:938508548797:web:6e0c2e7a3e61bf9dc815d4',
    messagingSenderId: '938508548797',
    projectId: 'activity-app-62503',
    authDomain: 'activity-app-62503.firebaseapp.com',
    storageBucket: 'activity-app-62503.appspot.com',
    measurementId: 'G-3NH410V5DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLleUulq7FD6cZ1NWKVgDBogwXl6yVNA',
    appId: '1:938508548797:android:6777142ceaf460dec815d4',
    messagingSenderId: '938508548797',
    projectId: 'activity-app-62503',
    storageBucket: 'activity-app-62503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcof3-xuWBaFxoUDxgNvaHeNG_hMhvAM',
    appId: '1:938508548797:ios:02a7a384e2c09488c815d4',
    messagingSenderId: '938508548797',
    projectId: 'activity-app-62503',
    storageBucket: 'activity-app-62503.appspot.com',
    iosBundleId: 'com.example.proje',
  );
}
