// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```darts
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvSdaTYYu1GoavsZX59JnltsZGBEz-I8',
    appId: '1:152075493872:web:b58c0145c52843d43bbd35',
    messagingSenderId: '152075493872',
    projectId: 'cart-app-92c24',
    authDomain: 'cart-app-92c24.firebaseapp.com',
    storageBucket: 'cart-app-92c24.appspot.com',
    measurementId: 'G-Q28WG9ZXKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcYK64RxKgTiUmqwsrhunBQ5x8LKkb4E',
    appId: '1:152075493872:android:fa58d80f7f4b2e5d3bbd35',
    messagingSenderId: '152075493872',
    projectId: 'cart-app-92c24',
    storageBucket: 'cart-app-92c24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKPoqLOSyTSLmFjWoQRAUV2xmD-6vAZ9M',
    appId: '1:152075493872:ios:5b107ef673a2f7803bbd35',
    messagingSenderId: '152075493872',
    projectId: 'cart-app-92c24',
    storageBucket: 'cart-app-92c24.appspot.com',
    iosBundleId: 'com.example.proje',
  );

}